### ISSUE TITLE
License/Ability to reuse

### ISSUE THREAD

**Issue by mica-alex** [MCRcortex/nekodetector#11]
There is no license available on the repository. 

- Is it allowed/permissible to reuse this code? (Of course, with the credit/link given in all relevant file headers)

I maintain a small Minecraft launcher, and due to the ongoing incident, I have temporarily disabled mod pack loading functionality. 
I would like to be able to add this functionality to automatically check downloaded mods prior to launching the game and allowing them to execute. With little modification to Main.java, support can be added to invoke this from inside a Java application, such as launcher.

**Comment by Ghifari160** [comment]
I would also like to know the license for this repo. I'm currently working on a launcher that can be automated to look for incompatibilities between mods in a pack (i.e. which set of mods causes the game to refuse to launch).

**Comment by SylvKT** [comment]
I'm going to have to refuse to contribute to this project any further without a license for fear of DMCA.

**Comment by kittokin** [comment]
they added an MIT license from this pull request #22
 i guess we can close this issue
