### ISSUE TITLE
Jar file is not compiled

### ISSUE THREAD

**Issue by Source-Dom** [MCRcortex/nekodetector#12]
Hi, is there any way you could make a release, so that we directly have the compiled jar file, please ?

**Comment by killer2gudpl** [comment]
I agree! Would be a great help when checking for infected mods in a modpack. Myself included, as I have been creating a modpack over the past week.

**Comment by NeRdTheNed** [comment]
Here's a [snapshot build](https://github.com/MCRcortex/nekodetector/files/11680842/jarscanner-snapshot.zip), based on commit 21e6963.

**Comment by rferris** [comment]
`
git clone https://github.com/MCRcortex/nekodetector.git

`

**Comment by Huskydog9988** [comment]
we now have public releases https://github.com/MCRcortex/nekodetector/releases

**Comment by BUNGAANTIKA** [comment]
i have same problem
