### ISSUE TITLE
weird gui glitch (big white box in front of text)

### ISSUE THREAD

**Issue by SylvKT** [MCRcortex/nekodetector#19]
what ze fuque
![image](https://github.com/MCRcortex/nekodetector/assets/18603248/04d44bd7-d22e-4b68-aa32-7eb297ce022d)
## steps to reproduce
- hint: try running it twice?
- i ran it again and i can't see any text in the output
- update: i have to select the text (click & drag)

im on `Linux 6.3.5-arch1-1`

**Comment by SticksDev** [comment]
linux skill issue, blame display servers and swing

**Comment by SylvKT** [comment]
Fixed somehow
