### ISSUE TITLE
Failed to scan mod: Terralith

### ISSUE THREAD

**Issue by GalaxySynth** [MCRcortex/nekodetector#24]
![image](https://github.com/MCRcortex/nekodetector/assets/73800917/6a2afd90-004b-4d3d-9d9a-eb80ce80c0e7)

Error only occurs with this mod.

**Comment by netnpathfinder** [comment]
I also got this error 
![image](https://github.com/MCRcortex/nekodetector/assets/54681529/d32d6b82-7d17-42b7-8280-58e316ed3c30)

**Comment by WFPhantom** [comment]
I think that might have something to do with terralith being a datapack packaged as a mod, its not exactly a mod afaik

**Comment by Huskydog9988** [comment]
The detector should be able to open the jars anyway regardless if they are an mc mod or not. My leading theory is that they were obfuscated/compiled in a way that the ClassLoader doesn't like.

**Comment by 0dinD** [comment]
Since the mod in question is Terralith, it might be related to douira/fractureiser-web-detector#6.

I suppose it would be pretty easy to check, just remove the `__MACOSX` folder from the JAR (if it exists) and try again.
