### ISSUE TITLE
Stuck on 1.2.5 JAR mod PlayerAPI

### ISSUE THREAD

**Issue by Nolij** [MCRcortex/nekodetector#25]
Tried running multiple times, consistently gets stuck on this one JAR. 
[PlayerAPI.zip](https://github.com/MCRcortex/nekodetector/files/11682624/PlayerAPI.zip)

Oddly enough this doesn't happen if I scan just that file or even just that directory.

JStack output if it helps:
[log.log](https://github.com/MCRcortex/nekodetector/files/11682641/log.log)

I ran with 32T but it also happens on 8T and even 1T, so I don't think it's a race condition.

**Comment by SylvKT** [comment]
What is your Operating System and how do we reproduce this?

**Comment by embeddedt** [comment]
Arch Linux

**Comment by Nolij** [comment]
Not sure what fixed it but the latest pre-release (1.1) works without issues now.
