### ISSUE TITLE
Failed to access file (C:/ or D:/)

### ISSUE THREAD

**Issue by Faller8** [MCRcortex/nekodetector#56]
Whenever I am scanning C:\ or D:\ this error pops up. So, I ran a scan in documents it worked. Then, I tried running the scan in Program Files but then also it said "Failed to access file".  I also tried running with command prompt but then this error showed up - Unable to access jarfile scanner.jar

**Comment by RoseApollo** [comment]
if your scanning the entire disk, you should open it as administrator, when running from command prompt, you will want to pass in the full path to scanner.jar eg: c:/users/me/downloads/scanner.ja

**Comment by Faller8** [comment]
Thank you so much, it is working.

**Comment by Faller8** [comment]
I don't know why but this morning I tried running the scanner again with the same instructions, but it doesn't seem to work (it worked yesterday when I followed those instructions).
