### ISSUE TITLE
Where is the Scanner.jar file?

### ISSUE THREAD

**Issue by somedude3452** [MCRcortex/nekodetector#60]
I have no idea how to run this scanner and the information provided is no help either.
Ive downloaded the zip unpacked it and tried to find ths scanner.jar file but it´s nowhere to be found.
Would be nice if there was a step by step instruction how to use this software.

**Comment by Faller8** [comment]
Looks like you have downloaded the wrong documents, you have downloaded the code files. Refer to this link -https://github.com/MCRcortex/nekodetector/releases Then click on the assets option. Then click on the .jar file and save it in your desired location, if a box doesn't appear after clicking the .jar file then check your download folder.

**Comment by Faller8** [comment]
As for the tutorial, after downloading the .jar file, open command prompt as administrator and then type - 'java -jar scanner.jar 4 C:\ ' without the apostrophe.

**Comment by somedude3452** [comment]
Thanks for the help i was really confused

**Comment by Faller8** [comment]
You're welcome, did it detect anything?

> Thanks for the help i was really confused

**Comment by somedude3452** [comment]
it´s currently scanning

**Comment by somedude3452** [comment]
Scan complete. No infected jars found. nice

**Comment by Faller8** [comment]
> Scan complete. No infected jars found. nice

If you have any other drives you want to scan just copy the same command but replace the C:\ with the drive name in command prompt.

**Comment by somedude3452** [comment]
Ok good to know :)
